### ISSUE TITLE
about pwa studio custom payment method

### ISSUE THREAD

**Issue by zouhongzhao** [larsroettig/create-pwa-studio-extension#19]
Hello, because I don't have your email address, I can't contact you. I can only ask you through the issues of this github. Sorry for the inconvenience.

This is my first contact with pwa studio. Currently, there is a need to customize the payment method, which needs to be paid online. I have been researching for 2 months and have not found any suitable information until I found your article, https://larsroettig.dev/demystified-pwa-studio-checkout. Very useful, but there are many places in this article where the code is incomplete, only a part of the code, so I don't know how to do it.

for example:

import { usePlaceOrderButton } from '../talons/usePlaceOrderButton';
importPath: '@my-payment/src/components/placeOrderButtonExpress.js'
etc. Many files are not there, don't know what the contents of these files are.

The code for usePlaceOrderButton and placeOrderButtonExpress.js is not seen in the article.

Can you give me a complete sample code? Grateful.
My email: [zouhongzhao@126.com](mailto:zouhongzhao@126.com)
Thank you

**Comment by larsroettig** [comment]
Please do not open tickets with support requests, I will not answer them here.
