### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Frodigo** [larsroettig/create-pwa-studio-extension#2]
The generated code by the generator contains the LICENSE file. I understand that this license is for a generator, and I am not sure if people who want to use the generator to write their own extension will find this file useful.

Perhaps the author's name, which we enter in the console when generating the project, should be displayed in the LICENSE file instead of the name of the author of the generator.

**Comment by larsroettig** [comment]
Hi @Frodigo, good catch looks like this file is generated by `npm registry` because it doesn't exit in the template folder itself

**Comment by larsroettig** [comment]
Will fix this issue in next 2-3 days thank you for report
